#!/bin/bash

export CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK
echo "mpi node $OMPI_COMM_WORLD_NODE_RANK, process $OMPI_COMM_WORLD_LOCAL_RANK : CUDA_VISIBLE_DEVICES is $CUDA_VISIBLE_DEVICES"

$@
